## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

baseURL = "https://nigelswab.github.io/"
languageCode = "en"
title = "Nigel Swab - Mechanical Engineer"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  github = "https://https://github.com/nigelswab"
  twitter = "https://twitter.com/caressofsteel_"
  email = "nigelswab@gmail.com"
  instagram = "https://instagram.com"
  linkedin = "https://www.linkedin.com/in/nigel-swab/"
  telegram = "https://telegram.org"